apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: bookinfo-circuit-breaker
spec:
  destination:
    name: reviews
    labels:
      version: v1
  circuitBreaker:
    simpleCb:
      # Maximu number of connections on destination backend
      maxConnections: 1
      # Maximum number of pending requests to destination backend
      httpMaxPendingRequests: 1
      # Minimum time circuit will be opened
      sleepWindow: 3m
      # Time between ejection sweep analysis
      httpDetectionInterval: 1s
      # Maximum percentage of hosts to eject if circuit is triggered
      httpMaxEjectionPercent: 100
      # Number of 5XX codes before circuit should be opened
      httpConsecutiveErrors: 1
      # Max number of requests per connection to a backend
      httpMaxRequestsPerConnection: 1
